Add user system + api token
evntboard/core pull request #8
Opened 2023-10-25 15:21 UTC by Tilican

2023-10-26 13:10 UTC, shiipou requested changes

2023-10-26 13:10 UTC, shiipou commented on auth.go
> +	err = SendEmail("moi@moi.fr", email, "Your password has been reset", fmt.Sprintf("Your new password is : %s", newPassword))
`moi@moi.fr` ?

2023-10-26 13:10 UTC, shiipou commented on auth.go
> +	result := db.Where("email = ?", email).Limit(1).Find(&user)
You didn't execute the bcrypt if the email didn't exist in the db.
You have to make it even if you didn't use it. Because that allow hacker to find emails if they try because of the time difference between the valid and invalid email request that thr server take to answer a request.

2023-10-26 13:10 UTC, shiipou commented on email.go
> +	smtpHost = os.Getenv("EVNTBOARD_SMTP_HOST")
Is this not better to write a Config struct that will parse each env usable in the project in the same place ? Better to find what we can configure as a dev.

2023-10-26 13:10 UTC, shiipou commented on frontend/src/component/diffEditor/DiffEditor.jsx
> +  const userTheme = user?.data?.ide_theme ?? 'light'
Why not use thr system theme as default ?

2023-10-26 13:10 UTC, shiipou commented on frontend/src/hook/event.js
> +    const source = new EventSourcePolyfill('/api/event/sse', { headers: { 'Authorization': localStorage.getItem('token') ?? '' } })
Did you ask the user before saving in the localStorage ? You have to let the user accept it by checking the "Remember me" checkbox at login. If not, it must only be in a struct to be stored in RAM and not in storage.

2023-10-27 12:35 UTC, Tilican commented on frontend/src/component/diffEditor/DiffEditor.jsx
> +  const userTheme = user?.data?.ide_theme ?? 'light'
ide_theme should always be set, but in case I add this

2023-10-27 12:36 UTC, Tilican commented on frontend/src/hook/event.js
> +    const source = new EventSourcePolyfill('/api/event/sse', { headers: { 'Authorization': localStorage.getItem('token') ?? '' } })
nope, i'll make it later in another MR

2023-10-27 13:17 UTC, merged